### ISSUE TITLE
Participation certificates: people without results

### ISSUE THREAD

**Issue by AlexKatyukov** [Goosly/wca-certificates#26]
_#9 — here is initial issue._

If competitor didn't took part in any event, his certificate generates anyway. 
![image](https://user-images.githubusercontent.com/18090165/77068088-0f22d100-69f7-11ea-9016-fbefca72c723.png)

**Comment by Goosly** [comment]
Hm, what do you think should happen if there are no results _at all_ (like, before the competition)?
It would still be good to be able to print them before the competition, so that you can check that it looks okay (for example if you made a custom background). But if we just filter out everyone without results, there would be nothing to print.

**Comment by AlexKatyukov** [comment]
Hmm. Don't know to be honest, I even don't think that someone can want to generate blank certificates.
Maybe something like this:

1. If there are some results — print only persons who have results
2. If there are no any results — give an opportunity to select:
2.1. Print one certificate with some standart name and table with all events of competition results 
2.2. Print all certificates and not to output results table (for users who wants go generate such certificates prior to competition). User should edit text himself.

**Comment by Goosly** [comment]
For now I've kept it simple, the button will just be disabled when there is nothing to print (= before the competition, when there are no results yet). If someone _really_ wants to test it, they can enter one fake result in WCA Live I guess...

![image](https://user-images.githubusercontent.com/12575384/77448254-d6b53580-6df0-11ea-9463-fd31424b762d.png)
